# Generated by Django 5.1.6 on 2025-03-02 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=300)),
                ("Description", models.TextField()),
                ("CreateDate", models.DateField(auto_now_add=True)),
                ("StartDate", models.DateField()),
                ("EndDate", models.DateField()),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("Members", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=200)),
                ("Description", models.TextField()),
                ("CreateDate", models.DateField(auto_now_add=True)),
                ("StartDate", models.DateField()),
                ("EndDate", models.DateField()),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("Members", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                (
                    "ParentProject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashbord.project",
                    ),
                ),
            ],
        ),
    ]
