# Generated by Django 5.1.6 on 2025-03-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashbord", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="Slug",
            field=models.SlugField(default=""),
        ),
        migrations.AddField(
            model_name="task",
            name="Slug",
            field=models.SlugField(default=""),
        ),
    ]
