# Generated by Django 5.1.6 on 2025-03-09 06:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashbord", "0002_project_slug_task_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Project",
            new_name="ProjectModel",
        ),
        migrations.RenameModel(
            old_name="Task",
            new_name="TaskModel",
        ),
    ]
