# Generated by Django 5.1.6 on 2025-03-09 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashbord", "0003_rename_project_projectmodel_rename_task_taskmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectmodel",
            old_name="Slug",
            new_name="slug",
        ),
        migrations.RenameField(
            model_name="taskmodel",
            old_name="Slug",
            new_name="slug",
        ),
    ]
