# Generated by Django 5.1.6 on 2025-03-09 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashbord", "0004_rename_slug_projectmodel_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmodel",
            name="ParentProject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="dashbord.projectmodel",
            ),
        ),
    ]
