# Generated by Django 5.1.6 on 2025-03-14 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashbord", "0005_alter_taskmodel_parentproject"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmodel",
            name="Members",
            field=models.ManyToManyField(
                related_name="projectMember", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="projectmodel",
            name="slug",
            field=models.SlugField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="Members",
            field=models.ManyToManyField(
                related_name="taskMember", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="slug",
            field=models.SlugField(default="", null=True),
        ),
    ]
