# Generated by Django 5.1.6 on 2025-03-15 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashbord",
            "0006_alter_projectmodel_members_alter_projectmodel_slug_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name="projectmodel",
            name="slug",
            field=models.SlugField(default=""),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="slug",
            field=models.SlugField(default=""),
        ),
        migrations.AddField(
            model_name="taskmodel",
            name="Category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="dashbord.category",
            ),
        ),
    ]
