# Generated by Django 5.1.6 on 2025-03-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashbord", "0009_alter_projectmodel_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmodel",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
