# Generated by Django 5.1.6 on 2025-03-17 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashbord", "0010_alter_projectmodel_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmodel",
            name="Admin",
            field=models.ManyToManyField(
                related_name="taskAdmin", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
