# Generated by Django 5.1.6 on 2025-03-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_user_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
