# Generated by Django 5.1.6 on 2025-03-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_user_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="Information",
            field=models.TextField(default="im using u-do in my job!"),
        ),
    ]
