# Generated by Django 5.1.6 on 2025-03-16 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ImgName',
            field=models.ImageField(upload_to='uploads/userImage'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
