# Generated by Django 5.1.6 on 2025-03-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_imgname_alter_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ImgName',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/userImage'),
        ),
    ]
