# Generated by Django 5.1.6 on 2025-03-16 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_imgname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
