# Generated by Django 5.1.6 on 2025-03-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ImgName',
            field=models.ImageField(blank=True, default='userImage/default.jpg', null=True, upload_to='userImage'),
        ),
    ]
