# Generated by Django 5.1.7 on 2025-03-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_friendship"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Friendship",
            new_name="FriendshipModel",
        ),
    ]
