# Generated by Django 5.1.7 on 2025-03-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_rename_friendship_friendshipmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendshipmodel',
            name='request_code',
            field=models.CharField(default='', max_length=30),
        ),
    ]
