# Generated by Django 5.1.6 on 2025-03-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullName", models.CharField(max_length=300)),
                ("email", models.CharField(max_length=350)),
                ("subject", models.CharField(max_length=350)),
                ("message", models.TextField()),
                ("createdDate", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
